### ISSUE TITLE
ssh handshake failed unable to authenticate

### ISSUE THREAD

**Issue by vanhecke** [r0binak/xzk8s#1]
Any idea why I'm getting 

```
ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

while you would expect the following:
```
ssh: handshake failed: EOF
```

from xzbot?

**Comment by r0binak** [comment]
> Any idea why I'm getting 
> 
> 
> 
> ```
> 
> ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
> 
> ```
> 
> 
> 
> while you would expect the following:
> 
> ```
> 
> ssh: handshake failed: EOF
> 
> ```
> 
> 
> 
> from xzbot?

It looks like you're trying to authorize by username and password. However, this authorization method is disabled (at the Dockerfile level).

**Comment by vanhecke** [comment]
I'm pretty sure xzbot uses pubkey auth? https://github.com/amlweems/xzbot/blob/8ae5b706fb2c6040a91b233ea6ce39f9f09441d5/main.go#L201C8-L201C18

**Comment by r0binak** [comment]
> I'm pretty sure xzbot uses pubkey auth? https://github.com/amlweems/xzbot/blob/8ae5b706fb2c6040a91b233ea6ce39f9f09441d5/main.go#L201C8-L201C18

Are you using the `r0binak/xzk8s:v1` image? Also make sure you run xzbot without the seed parameter

**Comment by r0binak** [comment]
@vanhecke I recorded a little demo for you

https://github.com/r0binak/xzk8s/assets/80983900/6337e00d-8c19-45d1-8bb7-8186f56dc3f7

**Comment by sxyugao** [comment]
When I build image myself, I encountered the same issue. 

Then I diff the sshd version in our images -- your version is OpenSSH_9.7p1 Debian-3, OpenSSL 3.1.5 30 Jan 2024, while my version is OpenSSH_9.7p1 Debian-4, OpenSSL 3.2.2-dev.

I don't know if that's why we get different results.

**Comment by sxyugao** [comment]
I use the old version sshd and solved the issue.
